[build]
  base = "examples/react-app" # Set this to the directory containing your React app
  publish = "examples/react-app/build" # Update this to your build output directory
  command = "cd ../../packages/data && yarn build && cd ../layers && yarn build && cd ../../examples/react-app && yarn build" # Build dependencies and the project